/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.zscuh.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PolicyInfoAttOverlapNotPk generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`POLICY_INFO_ATT_OVERLAP_NOT_PK`")
public class PolicyInfoAttOverlapNotPk implements Serializable {

    private String policyId;
    private int coverage;
    private Date busStart;
    private Date busEnd;

    @Id
    @Column(name = "`POLICY_ID`", nullable = false, length = 4)
    public String getPolicyId() {
        return this.policyId;
    }

    public void setPolicyId(String policyId) {
        this.policyId = policyId;
    }

    @Column(name = "`COVERAGE`", nullable = false, scale = 0, precision = 10)
    public int getCoverage() {
        return this.coverage;
    }

    public void setCoverage(int coverage) {
        this.coverage = coverage;
    }

    @Column(name = "`BUS_START`", nullable = false)
    public Date getBusStart() {
        return this.busStart;
    }

    public void setBusStart(Date busStart) {
        this.busStart = busStart;
    }

    @Column(name = "`BUS_END`", nullable = false)
    public Date getBusEnd() {
        return this.busEnd;
    }

    public void setBusEnd(Date busEnd) {
        this.busEnd = busEnd;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PolicyInfoAttOverlapNotPk)) return false;
        final PolicyInfoAttOverlapNotPk policyInfoAttOverlapNotPk = (PolicyInfoAttOverlapNotPk) o;
        return Objects.equals(getPolicyId(), policyInfoAttOverlapNotPk.getPolicyId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPolicyId());
    }
}

