/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.zscuh.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * PolicySttDup1 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`POLICY_STT_DUP1`")
@IdClass(PolicySttDup1Id.class)
public class PolicySttDup1 implements Serializable {

    private String bank;
    private String client;
    private Timestamp sysBegin1;
    private Timestamp sysEnd1;
    private Timestamp transId;
    private String type;
    private Integer pay;

    @Id
    @Column(name = "`BANK`", nullable = false, length = 4)
    public String getBank() {
        return this.bank;
    }

    public void setBank(String bank) {
        this.bank = bank;
    }

    @Id
    @Column(name = "`CLIENT`", nullable = false, length = 4)
    public String getClient() {
        return this.client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    @Column(name = "`SYS_BEGIN1`", nullable = false)
    public Timestamp getSysBegin1() {
        return this.sysBegin1;
    }

    public void setSysBegin1(Timestamp sysBegin1) {
        this.sysBegin1 = sysBegin1;
    }

    @Column(name = "`SYS_END1`", nullable = false)
    public Timestamp getSysEnd1() {
        return this.sysEnd1;
    }

    public void setSysEnd1(Timestamp sysEnd1) {
        this.sysEnd1 = sysEnd1;
    }

    @Column(name = "`TRANS_ID`", nullable = false)
    public Timestamp getTransId() {
        return this.transId;
    }

    public void setTransId(Timestamp transId) {
        this.transId = transId;
    }

    @Column(name = "`TYPE`", nullable = true, length = 5)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "`PAY`", nullable = true, scale = 0, precision = 10)
    public Integer getPay() {
        return this.pay;
    }

    public void setPay(Integer pay) {
        this.pay = pay;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PolicySttDup1)) return false;
        final PolicySttDup1 policySttDup1 = (PolicySttDup1) o;
        return Objects.equals(getBank(), policySttDup1.getBank()) &&
                Objects.equals(getClient(), policySttDup1.getClient());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBank(),
                getClient());
    }
}

